apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbitmq
spec:
  selector: # Deploymeny objesi pod ları yakalayabilmek için eşleşme arıyor.
    matchLabels:
      service: pod-deployment-rabbitmq
  template: # Buradan itibaren pod ile alakalı özellikleri yazıyoruz.
    metadata:
      labels: # bir pod un etiketi.
        service: pod-deployment-rabbitmq
    spec:
      containers:
      - name: pod-rabbitmq # pod un adı
        image: rabbitmq:3.13.0-management-alpine  # hub.docer üzerindeki image dı (mongo, redis, elasticsearch)
        resources:
          limits:
            memory: "1024Mi" # node ın total ram inden ne kadar kullanılacağı
            cpu: "100m" # node vCpu su 2 ise bu -> 2000M demektir.
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env: # işletim sistemine eklemek istediğiniz environmentvariable listesini ekliyoruz.
          - name: RABBITMQ_DEFAULT_USER
            value: admin
          - name: RABBITMQ_DEFAULT_PASS
            value: root

        