apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
spec:
  replicas: 1
  selector: # Deploymeny objesi pod ları yakalayabilmek için eşleşme arıyor.
    matchLabels:
      service: pod-deployment-user
  template: # Buradan itibaren pod ile alakalı özellikleri yazıyoruz.
    metadata:
      labels: # bir pod un etiketi.
        service: pod-deployment-user
    spec:
      containers:
      - name: pod-user # pod un adı
        image: javaboost2/user-service:v.0.2 # hub.docer üzerindeki image dı (mongo, redis, elasticsearch)
        resources:
          limits:
            memory: "1024Mi" # node ın total ram inden ne kadar kullanılacağı
            cpu: "150m" # node vCpu su 2 ise bu -> 2000M demektir.
        ports:
        - containerPort: 9094
        env: # işletim sistemine eklemek istediğiniz environmentvariable listesini ekliyoruz.
          - name: CONFIG_SERVER
            value: http://service-config:8888

        