kind: Service
apiVersion: v1
metadata:
  name: service-user # Servis objesinin adını belirliyoruz
spec:
  selector: # Kendisine bağlanacak olan podları seçebilmesi için label ekliyoruz.
    service: pod-deployment-user
  type: LoadBalancer # Servis Objesinin türünü belirtiyoruz.[LoadBalancer, ClusterIP, NodePort]
  ports:
  - name: user
    port: 9094 # servis e yapılacak olan isteklerin portu
    targetPort: 9094 # Bu port kendisine bağlanan pod ların portları olmak zorundadır.